import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Sidebar from "@/Components/Sidebar";

const poppins = Poppins({
  weight: "100",
});

export const metadata: Metadata = {
  title: "Fitness App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex">
          <Sidebar />
          <div className="w-full bg-[#F6F9F2]">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
